### ISSUE TITLE
results

### ISSUE THREAD

**Issue by mjanddy** [lucifer443/EfficientDet-Pytorch#1]
Have you get the result as the paper?

**Comment by lucifer443** [comment]
The model is still in training. I will update the result as soon as possible.

**Comment by lucifer443** [comment]
> Have you get the result as the paper?

The result is update.

**Comment by mjanddy** [comment]
> > Have you get the result as the paper?
> 
> The result is update.

how epochs you train? That is 300 epochs? and need I  decay lr ?

**Comment by lucifer443** [comment]
> Have you get the result as the paper?
> 
> The result is update.
> 
> how epochs you train? That is 300 epochs? and need I  decay lr ?

You can find training schedule in config file.

**Comment by mjanddy** [comment]
> > Have you get the result as the paper?
> > The result is update.
> > how epochs you train? That is 300 epochs? and need I  decay lr ?
> 
> You can find training schedule in config file.

if I use your config and  do not modify any thing, can I get the d0 map32?

**Comment by lucifer443** [comment]
> Have you get the result as the paper?
> The result is update.
> how epochs you train? That is 300 epochs? and need I  decay lr ?
> 
> You can find training schedule in config file.
> 
> if I use your config and  do not modify any thing, can I get the d0 map32?

The training procedure is not stable. The final mAP maybe between 31~32.
